apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-basics-app
  namespace: argocd
  # Finalizer ensures the Application is deleted properly
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project to which this application belongs
  project: default

  # Source repository configuration
  # Only sync resources from terraformdeployment directory
  # ArgoCD will automatically track and prune resources it created from this path
  source:
    repoURL: https://github.com/aayush0325/kubernetes-basics.git
    targetRevision: main
    path: terraformdeployment
    # Directory-based application - only resources in terraformdeployment are managed
    directory:
      recurse: true
      include: "*.yaml,*.yml"

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # Sync policy for automated deployments and self-healing
  syncPolicy:
    automated:
      # Automatically sync when Git repository changes
      prune: true
      # Self-healing: automatically sync when cluster state deviates from Git
      selfHeal: true
      # Allow empty resources (optional, useful for initialization)
      allowEmpty: false
    
    # Sync options for declarative management
    syncOptions:
      # Create namespace if it doesn't exist
      - CreateNamespace=true
      # Validate resources before applying
      - Validate=true
      # Use server-side apply for better conflict resolution
      - ServerSideApply=true
      # Prune last to avoid dependency issues (ensures resources are deleted after dependencies)
      - PruneLast=true

    # Retry policy for failed syncs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment and status
  ignoreDifferences: []

  # Revision history limit
  revisionHistoryLimit: 10

